name = "https-mobicycle-usa"
compatibility_date = "2025-09-01"
main = "_worker.js"

# [placement]

# [vars]
# MY_VARIABLE = "production_value"

# [ai]
# binding = "AI"

# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"
# script_name = 'my-durable-object'

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
